<Project>
  <PropertyGroup>
    <RepositoryRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RepositoryRoot>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <Version Condition="'$(Version)' == ''">0.0.0</Version>
    <CommonOutput Condition="'$(CommonOutput)' == ''">false</CommonOutput>
    <CommonOutputPath>$(RepositoryRoot)artifacts\common_output</CommonOutputPath>
    <CommonOutputManifestPath>$(RepositoryRoot)artifacts\common_output.manifests</CommonOutputManifestPath>
    <CommonOutputLockFile>$(RepositoryRoot)artifacts\common_output.lock</CommonOutputLockFile>
    <ApiSnapshotRepository Condition="'$(ApiSnapshotRepository)' == ''">Albeoris/Memoria.NeverwinterNights</ApiSnapshotRepository>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <BaseOutputPath>$(RepositoryRoot)artifacts\msbuild\$(MSBuildProjectName)\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepositoryRoot)artifacts\msbuild\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <WorkshopAppId>704450</WorkshopAppId>
  </PropertyGroup>
</Project>
