// Original work Copyright (c) 2020 Mischa Dutzik (Ravick).
// Relicensed under the MIT License by Albeoris. See THIRD_PARTY_NOTICES.md.

#include "m_lse_lib"

void main()
{
    string sConv = GetScriptParam("M_LSE_CONV");
    if (sConv == "m_lse_config")
    {
        SetCustomToken(303900, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_CLOSE));
        SetCustomToken(303901, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_OPTION));
        SetCustomToken(303902, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION));
        SetCustomToken(303911, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION_INCREASE_1));
        SetCustomToken(303912, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION_INCREASE_10));
        SetCustomToken(303913, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION_INCREASE_100));
        SetCustomToken(303914, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION_DECREASE_1));
        SetCustomToken(303915, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION_DECREASE_10));
        SetCustomToken(303916, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_OPTION_DECREASE_100));
        SetCustomToken(303951, M_LSE_SIN_GetText(M_LSE_STRREF_TOOLS_LABEL_DESTROY_CORPSE));
        SetCustomToken(303952, M_LSE_SIN_GetText(M_LSE_STRREF_TOOLS_LABEL_DESTROY_CORPSES_AREA));
        SetCustomToken(303953, M_LSE_SIN_GetText(M_LSE_STRREF_TOOLS_LABEL_DESTROY_CORPSES_ALL));
        SetCustomToken(303100, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_BACK));
        SetCustomToken(303101, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_TREASURE_SCANNING));
        SetCustomToken(303102, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_TREASURE_TRACKING));
        SetCustomToken(303103, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_TREASURE_LOOTING));
        SetCustomToken(303104, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_LOOTABLE));
        SetCustomToken(303105, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_DECAYING_LOOTED));
        SetCustomToken(303106, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_DECAYING_TIMED));
        SetCustomToken(303107, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_RAISEABLE));
        SetCustomToken(303108, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_LOOTING_EXAMINED));
        SetCustomToken(303109, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_LOOTING_KILLED));
        SetCustomToken(303110, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_CORPSE_LOOTING_KILLED_BY_HENCH));
        SetCustomToken(303111, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_ITEM_DESCRIPTION_ACQUIRED));
        // SetCustomToken(303112, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_FEATURE_ITEM_DESCRIPTION_VALUE));
        SetCustomToken(303120, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_BACK));
        SetCustomToken(303121, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_DELAY_CORPSE_DECAY));
        SetCustomToken(303121, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_DELAY_CORPSE_DECAY));
        SetCustomToken(303122, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_THRESHOLD_ITEM_PRICE));
        SetCustomToken(303123, M_LSE_SIN_GetText(M_LSE_STRREF_CONFIG_LABEL_PARAM_THRESHOLD_ITEM_WEIGHT));
        SetCustomToken(303601, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_001));
        SetCustomToken(303602, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_002));
        SetCustomToken(303603, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_003));
        SetCustomToken(303604, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_004));
        SetCustomToken(303605, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_005));
        SetCustomToken(303606, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_006));
        SetCustomToken(303607, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_007));
        SetCustomToken(303608, M_LSE_SIN_GetText(M_LSE_STRREF_TUTORIAL_008));

        SetCustomToken(303201, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_TREASURE_SCANNING)));
        SetCustomToken(303202, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_TREASURE_TRACKING)));
        SetCustomToken(303203, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_TREASURE_LOOTING)));
        SetCustomToken(303204, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_LOOTABLE)));
        SetCustomToken(303205, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_DECAYING_LOOTED)));
        SetCustomToken(303206, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_DECAYING_TIMED)));
        SetCustomToken(303207, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_RAISEABLE)));
        SetCustomToken(303208, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_LOOTING_EXAMINED)));
        SetCustomToken(303209, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_LOOTING_KILLED)));
        SetCustomToken(303210, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_CORPSE_LOOTING_KILLED_BY_HENCH)));
        SetCustomToken(303211, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_ITEM_DESCRIPTION_ACQUIRED)));
        // SetCustomToken(303212, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_FEATURE_ITEM_DESCRIPTION_VALUE)));
        SetCustomToken(303221, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_PARAM_DELAY_CORPSE_DECAY)));
        SetCustomToken(303222, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_PARAM_THRESHOLD_ITEM_VALUE)));
        SetCustomToken(303223, IntToString(M_LSE_GetConfigInt(M_LSE_LOCAL_PARAM_THRESHOLD_ITEM_WEIGHT)));
    }
}